### ISSUE TITLE
App does not display synced items without a sync once relaunched

### ISSUE THREAD

**Issue by enwin** [wallabag/windows-app#12]
Using a low end device, the app is resuming each time I open it, even when I just lock the screen when being on the app. When I unlock the screen, the app restart from zero even if I was reading an item.

The real problem for me is that every time the app relaunch I have to fetch the items again. If I dont do that I stay with blank 'unread', 'favourites' and 'archive' sections. When the phone has connectivity its ok but when I'm offline (like in the metro) I cant access any item.

Step to reproduce:

1. deactivate the refresh on startup option
* ensure items are synced
* completely close the app
* start the app
* notice that no items are visible

Phone: Lumia 535 Denim
App version: `1.5.0.0`

**Comment by jlnostr** [comment]
Thanks for this report. Submitted 1.5.0.1 to the store, should arrive soon :-)

**Comment by enwin** [comment]
Thanks for the update! It looks like its working good for me, got to test it once in the metro to be 100% sure :smile: 

During my tests I had one or twice the problem back but I can't figure out the steps to reproduce it so I'd say its good for me anyway.

Got another bug partially related that when in reading mode, if I lock the screen, once I unlock the phone the app is closed, I can see the end of the closing transition. When I start the app again the sections are empty again.

Should I create an other issue for this or do you think its related?

Thanks again for your rapidity!

**Comment by jlnostr** [comment]
I think it's better to create another issue for that problem, which seems to be related.
The ugly thing is that during debugging I never had this issue :D

**Comment by enwin** [comment]
Issue #14 created.

Good luck with this one :confused:

**Comment by jlnostr** [comment]
Thanks :)
