### ISSUE TITLE
App on reading mode is crashing when locking the phone

### ISSUE THREAD

**Issue by enwin** [wallabag/windows-app#14]
Steps to reproduce:

1. Open the app
* refresh list of item if needed
* select an item to read
* lock the phone
* unlock the phone
* notice that the app is closed and that you're on the home screen (sometimes I can see the end of the 'opening' animation of the homescreen playing )
* when starting the app again all sections are empty

Phone: Lumia 535 Denim
App version: `1.5.0.1`

**Comment by enwin** [comment]
I've found that the same happen when in the reading mode and switching to another app or going back to the homescreen.

**Comment by jlnostr** [comment]
Finally found the error. This time I need a bit more time to fix it.

**Comment by jlnostr** [comment]
Got it almost. I think the update could be released tomorrow.
Could you please translate "Loading..." into french? Thanks in advance!

**Comment by enwin** [comment]
That's great thanks!

For your translation, in this case we'd use "Chargement …"

Tell me if you want me to test this translation, my phone is english by default :smile:

**Comment by jlnostr** [comment]
First of all, sorry for the delay of the update.

Even if it is almost finished since last Sunday, there are still some bugs that needs to be fixed. Unfortunately, the school has priority. Hopefully I can fix them this week and submit the update to the store.

**Comment by enwin** [comment]
No problem at all! Thanks for the update.

**Comment by jlnostr** [comment]
Closed the issue now - update is submitted to the Store :)

**Comment by enwin** [comment]
Got the update, it looks great! Thanks!
