### ISSUE TITLE
unread list display duplicates on refresh

### ISSUE THREAD

**Issue by enwin** [wallabag/windows-app#16]
Hello.

First, thanks for the last update, I now can use the app in the metro \o/

Unfortunately I've got a small issue with the unread list.
Sometimes when I start the app (sorry I can't really find the correct walkthrough), upon refresh, the unread list gets duplicated.
I managed to get the same list displayed 3 times. The first duplication occurred on auto refresh (if I remember correctly) and the second duplication happened when I pressed the refresh button. I pressed the refresh button once more and I got the list without duplicates.

Sorry if I'm not really clear with that one ^^' don't hesitate to ask me some precisions if you need.

Thanks for all the good work on this app :smiley:

**Comment by jlnostr** [comment]
I know what you mean, I had this issue in testing, too.
But after one or two times it never came back again, so I thought, it is fixed ^^

Will look into it later this week, thanks for reporting! :+1:
