### ISSUE TITLE
Desktop application

### ISSUE THREAD

**Issue by jlnostr** [wallabag/windows-app#21]
[An user on twitter](https://twitter.com/riduidel/status/584993355819528192) wishes an desktop application for wallabag.
I think it could be realized easily, but it would need some extra time to make it work with the current `dev` branch.

And it makes no sense at the moment, because the client would be just a RSS reader.
It would make sense with wallabag v2, but then the client should work on Linux and Mac OS X, too.

**Comment by tcitworld** [comment]
>  It would make sense with wallabag v2, but then the client should work on Linux and Mac OS X, too.

Do you think the .NET components you use could be reused as Mono on Mac OS or Linux ?

**Comment by jlnostr** [comment]
The .NET components I'm currently using support Mono, too. So it shouldn't be a problem.

**Comment by tcitworld** [comment]
Oh, you mean I can try to compile it right now ?

**Comment by jlnostr** [comment]
You could try it, but it won't work. [Mono doesn't know anything about WPF](http://www.mono-project.com/docs/gui/wpf/) or Universal Apps at the moment. Basically it could compile, the GUI would be the dealbreaker.
The best solution for the desktop client is [GTK#](http://www.mono-project.com/docs/gui/), but it's not that comfortable like Universal apps and look horrible on Windows and Mac OS.

The best solution seems to be that another developer with knowledge of Python should do this thing. The GUI could be created with [PyQt](https://wiki.python.org/moin/PyQt) and it would look great on Windows, Linux and Mac OS.
