### ISSUE TITLE
https doesn't work

### ISSUE THREAD

**Issue by Pierrotd** [wallabag/windows-app#25]
Hi,
I've installed wallabag (1.9.1) on my own server. 
Before, I had a permanent redirection from http to https.
Unfortunately, that doesn't work with windows phone app.
I had suppressed the redirection only for wallabag, and that works.
Could you add the management of a certificate in the application?
Thanks.
Regards.

**Comment by jlnostr** [comment]
Just one question: Is it a self-signed certificate?

**Comment by Pierrotd** [comment]
The certicate has been signed by CACert.

**Comment by tcitworld** [comment]
Seems like you must first add CACert root certificates on your phone this way : http://answers.microsoft.com/en-us/mobiledevices/forum/mdlumia-mdupdate/adding-a-certificate-to-the-trusted-root/4aae16ce-6882-473a-90af-f83a82689c13?auth=1

If you don't, Windows sees it just like a self-signed certificate.

**Comment by jlnostr** [comment]
That's ugly. I'll look into it.

**Comment by jlnostr** [comment]
Well, I didn't refresh the page. If the solution of @tcitworld helped you, just leave a comment here.

**Comment by Pierrotd** [comment]
I have installed several certificates but that doesn't work.

**Comment by jlnostr** [comment]
Could you create a second user and send me the credentials to wallabag [at] jlnostr.de? This would it make a lot easier to look into the problem :)

**Comment by tcitworld** [comment]
Please write something in the documentation if you succeed.

@Pierrotd : Using CACert and owning a Windows Phone is not common ;) . I recommend using [Let's Encrypt](https://letsencrypt.org/) as soon as it's available, and hopefully Windows will include it's root certificates.

**Comment by Pierrotd** [comment]
@jlnostr: mail sent with 2nd user.

**Comment by jlnostr** [comment]
Update submitted to the store - thanks for the demo account :-)

**Comment by Pierrotd** [comment]
Thanks!
