### ISSUE TITLE
Wrong characters in french store description

### ISSUE THREAD

**Issue by jlnostr** [wallabag/windows-app#41]
As @j0k3r pointed out [here](https://github.com/wallabag/windows-app/pull/40/files#r43035740), the characters in the [french store description](https://github.com/wallabag/windows-app/blob/v2/store/App%20descriptions/fr_FR.md) are wrong. 
There aren't that much characters that are wrong, but I don't know french, so I leave this issue open for someone else :D

**Comment by j0k3r** [comment]
Does it break text inside the app or is it ok?

**Comment by jlnostr** [comment]
It's only used on the store, so it doesn't influence the app itself :)

**Comment by jlnostr** [comment]
Fixed with #42.
