### ISSUE TITLE
Feature request: Include date format in app localization

### ISSUE THREAD

**Issue by JeffMelton** [wallabag/windows-app#43]
The date format in the current beta retains the format generally preferred by Europeans (dd.mm.yyy); will you consider either including a date preference or adjusting date format based on OS localization settings (mm.dd.yyyy is typical for EN-US)?

Screenshot from the article view:
![date_format](https://user-images.githubusercontent.com/165736/26944023-211b01fe-4c4d-11e7-81f2-a8aa73de1984.jpg)

**Comment by jlnostr** [comment]
Overlooked that specific detail, next release will use the date format used by the current culture.

Thanks for reporting! 👍
