### ISSUE TITLE
Setup of the application in Windows 10

### ISSUE THREAD

**Issue by m-dubois** [wallabag/windows-app#44]
Hello ! :)

I just installed the wallabag app on a device with Windows 10 (a tablet) and I can't setup the application.

It is well installed, but I can't find any way to tell where my server is, the token, ...

I think it would have worked in Windows 8 by sliding the app settings panel... but there is no such thing in Window 10 (or I didn't see... :p)

It would nice to give hints to the user in case of a fresh install... that would give a better UX :)

**Comment by m-dubois** [comment]
I found it ! :)

Sliding the top panel towards the bottom opens a top bar in which we can see the hamburger menu (settings menu). And there's the settings option in it.

So, my problem is solved.

But!... (there's always a "but" ;))

I think it would be easier for the user that installs the application to be driven for the application setup on the main screen

I close this issue. Feel free to create a new issue for the installation wizard :)

**Comment by tcitworld** [comment]
New version (for wallabag v2) is quite different.

**Comment by m-dubois** [comment]
I will take a look when I upgrade my server :)
(and when it's released I guess :p)
Thanks for the info :)

**Comment by jlnostr** [comment]
@m-dubois In the meantime you can download the beta version for *wallabag v2* [from the Microsoft store](https://www.microsoft.com/store/apps/9nblggh5x3p6) and use the login data for <http://v2.wallabag.org>. Feel free to submit any kind of feedback :-)

@tcitworld And thanks for the fast response, maybe I should visit GitHub more often :wink:
