### ISSUE TITLE
What is the deleted articles category for ?

### ISSUE THREAD

**Issue by tcitworld** [wallabag/windows-app#54]
Though it's an interesting feature, I wonder what you plan to do with it ? Cancel articles that were accidentally deleted ? There may be too much of them after a while (and also, it takes memory on you device)

**Comment by jlnostr** [comment]
In earlier versions of wallabag v2 there were two methods to delete an article. Completely or just by marking it as deleted. The "deleted" filter is therefore deprecated and will be removed in the next version :)

**Comment by tcitworld** [comment]
Got it !
