### ISSUE TITLE
Provide a how-to to build the app

### ISSUE THREAD

**Issue by tcitworld** [wallabag/windows-app#55]
After dealing with Visual Studio for a while, I can't build the app (many assembly references are missing, references path is empty) . Could you provide instructions to build it from scratch ? And eventually provide some kind of config file so that my issue doesn't happen again?

**Comment by jlnostr** [comment]
Of course, shouldn't be a problem :)

**Comment by jlnostr** [comment]
Could you check if the [compiling guide in the wiki](https://github.com/wallabag/windows-app/wiki/Compiling) is working, please?

**Comment by tcitworld** [comment]
Yup, working. Since I had launched & tried to build without having SQLite installed, I had to delete it's reference and put it back.

Thanks for everything.
