### ISSUE TITLE
Adding an article with picture through the app doesn't show it in list view

### ISSUE THREAD

**Issue by tcitworld** [wallabag/windows-app#58]
Add an article through the app
Check on server that a picture is fetched
The picture isn't shown in the list view of the app.

**Comment by tcitworld** [comment]
With another article, it worked. :/

**Comment by jlnostr** [comment]
Maybe the image is still loading in background. Unlike browsers, the image only shows if it's loaded completely. Can you give me the specific URL where this bug occured?

**Comment by tcitworld** [comment]
The article was [this one](https://www.actualitte.com/article/monde-edition/contrer-les-stereotypes-par-les-livres-c-est-des-l-enfance-qu-ils-se-construisent/64058). I may have clicked on the article before it was fully loaded indeed. Can't this be done asynchronously ?

**Comment by jlnostr** [comment]
Okay, I can reproduce it. Will look into it.

**Comment by jlnostr** [comment]
Fixed it successfully :)
![image](https://cloud.githubusercontent.com/assets/5391936/13907096/d74b92a6-eee6-11e5-8ca9-dae362f6b694.png)
