### ISSUE TITLE
List view is buggy after a link is added

### ISSUE THREAD

**Issue by tcitworld** [wallabag/windows-app#59]
* Add a link inside the app
* View the new added link
* Return to list view
* Articles are show for a tenth of a second and then no article is shown (the new one like the old ones)
* Articles show up again if the filter is reset

No issues when the app is relaunched again.

**Comment by jlnostr** [comment]
Ah, that seems to be the reproduction for #56. I'll leave this issue open as a reminder and close #56 instead :)

**Comment by jlnostr** [comment]
So, it's not that you've added a link. Found the "real" steps for reproduction:

- Open the filter panel by clicking "items" in the top left corner
- Instantly close them by pressing the same button again
- Navigate to another page (settings or article)
- Navigate back, articles are missing
