### ISSUE TITLE
Fix handling of access token

### ISSUE THREAD

**Issue by jlnostr** [wallabag/windows-app#61]
After a certain amount of time, the app isn't handling the AccessToken and RefreshToken anymore (or wrong). The only way to fix this would be a relogin, which is hard because username and password aren't saved. And asking for them again and again is bad UX.

**Comment by tcitworld** [comment]
Why is this ? You should store the RefreshToken some place and use it to ask for a new AccessToken. Login and password really shouldn't be saved.

**Comment by jlnostr** [comment]
And that's what I'm currently doing and want to keep. Unfortunately, the server often returns "Invalid refresh token" and I'm sure it's my app fault. Therefore I need to look why this is happening, so that the user *doesn't* need to re-login.

**Comment by tcitworld** [comment]
> I'm sure it's my app fault.

Don't speak too fast, I didn't test that much that feature. ;-)

**Comment by jlnostr** [comment]
It's still isn't perfect when I'm trying to sync the tokens over the different devices. Reopened it.

**Comment by jlnostr** [comment]
Fixed. Although I needed to remove the authentication sync, cause it's way too slow and therefore wrong authentication data is synced which always required an annoying re-authentication.
