### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by abers** [wallabag/windows-app#66]
Been having difficulty getting the Windows 10 app to sync.

I have my URL that works in web browser and android. User ID I have as 1. Token I have the same one that works on Android. I have tried self-sign certificates on and off - but no matter what I set it to refresh apparently does nothing. There is no fail message or anything like that.

Not sure what else to try.

Edit: With the beta version I am getting a login failure message which I think is due to not really knowing what its expecting for Client ID and Client Secret.

**Comment by tcitworld** [comment]
At the moment, the Android app still uses the old auth system from v1. The Windows app is fully compatible v2 and uses oAuth.
You need to create new credentials for your client (the Windows app) at http://yourwallabag.tld/developer/client/create. It will give you a Client ID and Client Secret.

**Comment by abers** [comment]
Bingo! Great to see dark theme and text justification in the app as well. Thanks for all help today and yesterday.
