### ISSUE TITLE
App stopped syncing 

### ISSUE THREAD

**Issue by abers** [wallabag/windows-app#68]
Experiencing an issue with the Windows 10 beta app where it no longer syncs. Both my Windows 10 devices are affected whereas I can still access Wallabag fine from a web browser and through the Android app. If selecting "Logout" or "Delete local database" within the Windows 10 app, it closes the app and on relaunching it seems to automatically log back in (or at least I am not presented with any sign-in screen / prompt to add client ID and secret) and I am stuck with an empty screen since it doesn't successfully sync. No error messages are displayed when syncing - the arrows rotate for half a second and that's it - still left with a screen with zero items. At a loss for what else to try to resolve this issue.

**Comment by jlnostr** [comment]
Yep, that's a known issue. For now you can reset the app by deleting the credentials from the Windows credential store. It can be found in the control panel. I don't know the correct name in English, this is how it looks on my German machine:
![image](https://cloud.githubusercontent.com/assets/5391936/15818596/98b661d0-2bde-11e6-86dc-f8d6ab98762a.png)

The second step to do is to delete the database file (`wallabag.db`), it's stored in `C:\Users\%USERNAME%\AppData\Local\Packages\36523JulianOster.wallabag.Beta_sx05p2v2fvsbm\LocalCache`. When both steps are done, the app should present the login screen again :)

**Comment by jlnostr** [comment]
Can I close this issue now?
