### ISSUE TITLE
App crashing on Lumia 535 Denim

### ISSUE THREAD

**Issue by enwin** [wallabag/windows-app#9]
As soon as I start the app it closes. No error message, nothing. Just going back to the homescreen.

I tried to restart the phone and uninstall/reinstall the app without any improvement.

App version: `2015.129.1352.5725`

**Comment by jlnostr** [comment]
Thanks for the report. I only tried it on my Lumia 930 where everything was working. But on the Lumia 735 of my brother it shows the same behaviour as your phone.

I'll try to fix this as soon as possible. Sorry :(

**Comment by enwin** [comment]
Thanks. Happy debugging!

**Comment by plotters** [comment]
I saw this as well on a 1020 (with 8.1 denim). After it was installed for the firs time it worked fine. Then I re-installed it an it failed. It there a persistent SQLite database which is not deleted somewhere?

I am pretty new to windows phone development in general, but would like to help. So started to clone it into Visual studio. Does not work:

Error	1	Dieses Projekt verweist auf mindestens ein NuGet-Paket, das auf diesem Computer fehlt. Aktivieren Sie die Wiederherstellung von NuGet-Paketen, um die fehlende Datei herunterzuladen. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkID=322105". 

I installed the NuGet packages. Is there a simple tutorial how to get started? This would be much appreciated. Using Visual Studio 2013 community.

**Comment by jlnostr** [comment]
Okay, update created. Should fix the problem and will be published tomorrow :)

**Comment by jlnostr** [comment]
I am just leaving it open until you both can tell me that the app is working now.

**Comment by jlnostr** [comment]
Übrigens @plotters, wofür brauchst du ein Tutorial?

**Comment by plotters** [comment]
To get started with windows phone dev.
I could work out some translations: Dutch, Spanish.

**Comment by jlnostr** [comment]
Translations are perfect!

First of all, I don't know if you already have some knowledge in programming. If not, then start with some "Hello World" tutorials on the web. 

And if you want to make some changes to the wallabag app, then fork it first and perform a pull request if your changes/bugfix/optimization is finished.
I saw that you are new to GitHub. There are some great tutorials on the web for GitHub and working with Git.

Tobi (developer of Poki) can recommend the [Channel 9 videos of the MSDN](http://channel9.msdn.com/). I didn't watched them, therefore I cannot say everything about the quality.

If there are any questions, feel free to contact me :)

**Comment by jlnostr** [comment]
Okay, update is out. On the Lumia 735 it's now working.
How about you, @enwin?

**Comment by enwin** [comment]
Working like a charm! Many thanks. The app is now on my homescreen :wink:

**Comment by plotters** [comment]
Yes, works on 1020 as well. Nice! I have the app working in the simulator now in Visio. Will let you know when I have something ready.

**Comment by jlnostr** [comment]
Perfect! Then I'll close this issue.
